import request from "@/network/request"
const testAPI = require("@/apis")

export const getAllPurchase = config => request._get(testAPI.PURCHASE_ALL, config)
export const createPurchase = config => request._post(testAPI.PURCHASE_CREATE, config)
export const firstApproval = config => request._get(testAPI.PURCHASE_FIRST_APPROVAL, config)
export const secondApproval = config => request._get(testAPI.PURCHASE_SECOND_APPROVAL, config)
export const getAllPurchaseReturn = config => request._get(testAPI.PURCHASE_RETURN_ALL, config)
export const createPurchaseReturn = config => request._post(testAPI.PURCHASE_RETURN_CREATE, config)
export const returnFirstApproval = config => request._get(testAPI.PURCHASE_RETURN_FIRST_APPROVAL, config)
export const returnSecondApproval = config => request._get(testAPI.PURCHASE_RETURN_SECOND_APPROVAL, config)
export const getAllCustomer = config => request._get(testAPI.CUSTOMER_QUERY, config)
export const getPurchaseBySheetId = config => request._get(testAPI.PURCHASE_FIND_SHEET_BY_ID, config)
export const addNewCustomer = config => request._post(testAPI.ADD_CUSTOMER,config)
export const deleteCustomer = config => request._post(testAPI.DEL_CUSTOMER,config)
export const q_dao = config => request._post(testAPI.Q_DAO,config)
export const get_all_user = config => request._get(testAPI.GET_ALL_USER,config)
export const check_sign_in = config => request._post(testAPI.CHECK_SIGN_IN,config)
export const fire = config => request._post(testAPI.FIRE,config)
export const adjust = config => request._post(testAPI.ADJUST,config)
export const get_all_account = config => request._get(testAPI.GET_ALL_ACCOUNT,config)
export const add_account = config => request._post(testAPI.ADD_ACCOUNT,config)
export const adjust_account = config => request._post(testAPI.ADJUST_ACCOUNT,config)
export const del_account = config => request._post(testAPI.DEL_ACCOUNT,config)
export const make_collection_sheet = config => request._post(testAPI.MAKE_COLLECTION_SHEET,config)
export const get_collection_sheet_by_state = config => request._get(testAPI.GET_COLLECTION_SHEET_BY_STATE,config)
export const approval_collection_sheet = config => request._get(testAPI.APPROVAL_COLLECTION_SHEET,config)
export const make_purchase_sheet = config => request._post(testAPI.MAKE_PURCHASE_SHEET,config)
export const get_purchase_sheet_by_state = config => request._get(testAPI.GET_PURCHASE_SHEET_BY_STATE,config)
export const approval_purchase_sheet = config => request._get(testAPI.APPROVAL_PURCHASE_SHEET,config)
export const red_sale = config => request._post(testAPI.RED_SALE,config)
export const red_sale_return = config => request._post(testAPI.RED_SALE_RETURN,config)
export const red_purchase = config => request._post(testAPI.RED_PURCHASE,config)
export const red_purchase_return = config => request._post(testAPI.RED_PURCHASE_RETURN,config)
export const red_collection_sheet = config => request._post(testAPI.RED_COLLECTION_SHEET,config)
export const red_purchase_sheet = config => request._post(testAPI.RED_PURCHASE_SHEET,config)
export const red_wages_sheet = config => request._post(testAPI.RED_WAGES_SHEET,config)
export const get_salary_sheet_by_state = config => request._get(testAPI.GET_SALARY_SHEET_BY_STATE,config)
export const make_salary_sheet = config => request._post(testAPI.MAKE_SALARY_SHEET,config)
export const wages_first = config => request._get(testAPI.WAGES_FIRST,config)
export const wages_second = config => request._get(testAPI.WAGES_SECOND,config)
export const get_wages_sheet_by_state = config => request._get(testAPI.GET_WAGES_SHEET_BY_STATE,config)
export const ming_xi = config => request._get(testAPI.MING_XI,config)
export const ming_xi_return = config => request._get(testAPI.MING_XI_RETURN,config)
export const get_all_processing = config => request._post(testAPI.GET_ALL_PROCESSING,config)
export const find_all_salary_strategy = config => request._get(testAPI.FIND_ALL_SALARY_STRATEGY,config)
export const update_salary_strategy = config => request._post(testAPI.UPDATE_SALARY_STRATEGY,config)
export const find_year_end = config => request._get(testAPI.FIND_YEAR_END,config)
export const update_year_end = config => request._post(testAPI.UPDATE_YEAR_END,config)
export const sale_strategy = config => request._post(testAPI.SALE_STRATEGY,config)